### ISSUE TITLE
Constantly get HTTP 502 Bad Gateway Error on 3DS

### ISSUE THREAD

**Issue by n1vk** [smartperson/3DS-FBI-Link#6]
FBI Version: 2.6.1
macOS Version: Monterey 12.0.1
3DS Version: 11.15.0-47J; Luma Version: v10.1.3

---
On 3DS, I get following error:

Failed to install from URL [...]
Result code: 0xD963F9FE
Level: Permanent (27)
Summary: Internal (11)
Module: Application (254)
Desc: HTTP 502: Bad Gateway (510)

---
In 3DS-FBI-Link, I get:

Starting up.
Connected to 3DS at 192.168.1.103.
All consoles finished downloading.
Shutting down.

**Comment by n1vk** [comment]
It seems to be a FBI problem.

**Comment by etomarat** [comment]
@n1vk i have same issue. Do you have any solution?

**Comment by metalminx** [comment]
Nope. Sorry.
